### ISSUE TITLE
微博数据集地址失效

### ISSUE THREAD

**Issue by zyh3826** [FDChongLi/TwoWaysToImproveCSC#1]
微博数据集地址失效

**Comment by FDChongLi** [comment]
原始地址可能失效了，可以从这个仓库里下载微博数据集：https://github.com/codemayq/chinese_chatbot_corpus

**Comment by zyh3826** [comment]
> 原始地址可能失效了，可以从这个仓库里下载微博数据集：https://github.com/codemayq/chinese_chatbot_corpus

谢啦

**Comment by zyh3826** [comment]
> 原始地址可能失效了，可以从这个仓库里下载微博数据集：https://github.com/codemayq/chinese_chatbot_corpus

作者您好，插楼问个问题，能放出数据处理的脚本吗，或者说说数据咋处理的，readme里有点简单哈

**Comment by FDChongLi** [comment]
两个数据集的预处理方式大体上都相同，包含了分句、保留合适长度的句子。Wiki这个语料由于以繁体字为主，所以利用gensim抽取之后还需要用opencc进行繁简体转换。而Weibo这个数据集由于相对口语化，语法上不是那么严谨，其中也包含了一定的拼写错误，所以我们当时采用了训练得到的最好的CSC模型进行检查，仅保留了模型认为没有错别字的句子。

**Comment by zyh3826** [comment]
> 两个数据集的预处理方式大体上都相同，包含了分句、保留合适长度的句子。Wiki这个语料由于以繁体字为主，所以利用gensim抽取之后还需要用opencc进行繁简体转换。而Weibo这个数据集由于相对口语化，语法上不是那么严谨，其中也包含了一定的拼写错误，所以我们当时采用了训练得到的最好的CSC模型进行检查，仅保留了模型认为没有错别字的句子。

感谢

**Comment by zyh3826** [comment]
> 两个数据集的预处理方式大体上都相同，包含了分句、保留合适长度的句子。Wiki这个语料由于以繁体字为主，所以利用gensim抽取之后还需要用opencc进行繁简体转换。而Weibo这个数据集由于相对口语化，语法上不是那么严谨，其中也包含了一定的拼写错误，所以我们当时采用了训练得到的最好的CSC模型进行检查，仅保留了模型认为没有错别字的句子。

作者您好，关于pre-trainning的时候character substitution-based method有几个问题请教：
1. 文章中只说了一个句子的25%的字进行替换？那么对于训练集，测试集，验证集，是每一条数据都替换了25%的字？
2. OOV问题，即如果选中的词没有在困惑集中，是咋处理的呢
麻烦了

**Comment by FDChongLi** [comment]
1. 文章里提到的25%的字进行替换是指在生成伪训练样本时的参数设置，即输入一个句子我们随机选择25%的汉字进行替换。在预训练阶段选取生成的伪训练样本的一部分作为验证集。除了预训练阶段，其它微调的过程中不会对句子进行修改。
2. 如果选择的字没有在困惑集中，则略过即可。可以参考我们的实现思路，即打乱句子的下标，对打乱的下标进行遍历，如果字在困惑集中，则随机选择它的同音字/形近字(90%的概率)，或随机用一个不同的汉字进行替换(10%)；如果字不在困惑集中，则略过该字跳到下一个字，直到25%的字被替换。

**Comment by zyh3826** [comment]
> 1. 文章里提到的25%的字进行替换是指在生成伪训练样本时的参数设置，即输入一个句子我们随机选择25%的汉字进行替换。在预训练阶段选取生成的伪训练样本的一部分作为验证集。除了预训练阶段，其它微调的过程中不会对句子进行修改。
> 2. 如果选择的字没有在困惑集中，则略过即可。可以参考我们的实现思路，即打乱句子的下标，对打乱的下标进行遍历，如果字在困惑集中，则随机选择它的同音字/形近字(90%的概率)，或随机用一个不同的汉字进行替换(10%)；如果字不在困惑集中，则略过该字跳到下一个字，直到25%的字被替换。

收到，感谢

**Comment by ThuJiang** [comment]
> 1. 文章里提到的25%的字进行替换是指在生成伪训练样本时的参数设置，即输入一个句子我们随机选择25%的汉字进行替换。在预训练阶段选取生成的伪训练样本的一部分作为验证集。除了预训练阶段，其它微调的过程中不会对句子进行修改。
> 2. 如果选择的字没有在困惑集中，则略过即可。可以参考我们的实现思路，即打乱句子的下标，对打乱的下标进行遍历，如果字在困惑集中，则随机选择它的同音字/形近字(90%的概率)，或随机用一个不同的汉字进行替换(10%)；如果字不在困惑集中，则略过该字跳到下一个字，直到25%的字被替换。

您好，请问后续会release处理脚本以及数据吗。
