### ISSUE TITLE
请教下训练阶段的具体数据使用

### ISSUE THREAD

**Issue by NLPJCL** [FDChongLi/TwoWaysToImproveCSC#2]
您好，恭喜您中了顶会paper，很有意思的工作。我有一点问题请教一下。
1.您给的下载模型的网盘中，BERT文件夹下有三个文件(baseline,preTrain,advTrain),其中的baseline文件下，有四个文件（inital,sighan13,sighan14,sighan15）。请问下inital是否代表没有fintune的bert呢？sighan13,14,15是用什么数据，什么顺序训练过的模型呢？为什么要分开呢？不同测试集不用一个模型呢？

我下载了sighan15下的模型，并对data/15test.txt做预测，用cpu做预测，得到如下结果，感觉与paper中相应的结果对不上，不清楚是什么原因？
----Task: sighan15 begin !----
detection sentence accuracy:0.8354545454545454,precision:0.7482517482517482,recall:0.7896678966789668,F1:0.7684021543985636
correction sentence accuracy:0.8254545454545454,precision:0.7290209790209791,recall:0.7693726937269373,F1:0.748653500897666
sentence target modify:542,sentence sum:1100,sentence modified accurate:417

**Comment by FDChongLi** [comment]
谢谢！感谢您对我们的工作感兴趣 : )
1. 如您猜测的一样，initial是还没在对应训练集finetune的模型
2. sighan13、14、15的数据集是data目录下的数据集。数据集最初来自[SpellGCN](https://github.com/ACL2020SpellGCN/SpellGCN)开源的仓库里，如论文中描述的，这个数据集是经过Opencc繁简体转换后的数据集。我们在与原始繁体数据集对比后对数据集进行了校对，校对的修改记录放在“Data revision record”目录下。修改的主要原因则是由于“一简对多繁”现象导致了部分拼写错误消失，比如繁体字“復“与”複”都对应简体字“复”。
3. baseline模型首先在Wang等人于2018年生成的270K数据集上进行训练(initial)，接着在对应的训练集上进行finetune。而pretrain则是多了一个针对CSC设计的预训练阶段。这样安排的原因是我们认为不同的数据集的分布不同，需要在各自训练集上finetune。我们也发现Soft-masked bert与SpellGCN的训练方式可能有所区别，因此为了公平，我们对所有模型都采取了相同的训练方式再进行性能上的比较。
4. 由于我们论文中的结果是采用五个不同的随机种子训练后平均的结果，网盘里的模型只是一个随机种子产生的结果，因此模型结果的可能会有一点点差异。

**Comment by NLPJCL** [comment]
感谢回复！还有几个问题想再确认下。
1.您网盘中给的initial的模型是已经在Wang等人于2018年生成的270K数据集上进行训练过的模型，是这样吗？
2.请问下，您在训练Wang等人于2018年生成的270K数据集(阶段I)，和真实sighan13、14、15（阶段II）的具体的参数(batch_size,学习率)，另外，这两个阶段有区别吗？
3.请问下针对CSC任务设计的预训练阶段，训练的数据是提前处理好的静态数据，不是动态的在训练过程中处理数据，是这样吗？（因为貌似代码中没有看到针对预训练阶段动态处理的代码部分），如果方便的话，可以提供下预训练阶段的训练参数（学习率和batch_size）吗？

**Comment by FDChongLi** [comment]
1. 是的。
2. BERT和Soft-masked BERT两个阶段的学习率都为2e-5，batch_size为20，而SpellGCN的学习率是5e-5，batch_size由于显存限制降低到8。
3. 伪训练样本是提前生成好的静态数据，只不过随机种子不同会生成不同的伪训练样本(随机种子会影响在句子中随机挑选汉字的位置)。预训练阶段参数与回答2相同。

**Comment by NLPJCL** [comment]
收到，感谢！

**Comment by NLPJCL** [comment]
再请教下，
1.您在不同阶段：阶段1（wang18 27w数据）和阶段2（各自的sighan13,14,15数据）上的开发集选择和跑多少epoch的设置？谢谢啦、

**Comment by FDChongLi** [comment]
在阶段1的训练过程中我们随机抽取了1000个样本作为开发集，而在阶段2中我们沿用了SpellGCN的设置(即将测试集作为开发集)
